remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have onetitle: Sahi's portfolio
#logo:
description: Vous trouverez sur ce site mes différents projets personnels et des articles sur divers sujets.